import type { PipelineRow } from "./types";

export const PIPELINE_ROWS: PipelineRow[] = [
  {
    slug: null,
    project: "Chuan Grove Residences",
    segment: "Condo, D19",
    units: "~1,055",
    expected: "2H 2026",
    catalyst: "Short walk to Lorong Chuan MRT (Circle Line)",
    verdict: "PENDING",
    score: null,
    timingConfidence: "reported",
  },
  {
    slug: null,
    project: "Upper Thomson Residences",
    segment: "Condo, D20",
    units: "~595",
    expected: "Q4 2026",
    catalyst: "Mixed use, retail and childcare at ground level",
    verdict: "PENDING",
    score: null,
    timingConfidence: "reported",
  },
  {
    slug: null,
    project: "Dorset Road",
    segment: "Condo, RCR",
    units: "TBC",
    expected: "2H 2026",
    catalyst: "City fringe, UOL, SingLand and Kheng Leong",
    verdict: "PENDING",
    score: null,
    timingConfidence: "reported",
  },
  {
    slug: null,
    project: "Hougang Central",
    segment: "Condo, D19",
    units: "TBC",
    expected: "TBC",
    catalyst: "Integrated with bus interchange, mall, NEL and future CRL",
    verdict: "PENDING",
    score: null,
    timingConfidence: "reported",
  },
  {
    slug: null,
    project: "Woodlands Drive 17",
    segment: "EC, D25",
    units: "TBC",
    expected: "TBC",
    catalyst: "About 250m to Woodlands South MRT (TEL)",
    verdict: "PENDING",
    score: null,
    timingConfidence: "reported",
  },
  {
    slug: null,
    project: "Senja Close",
    segment: "EC, D23",
    units: "TBC",
    expected: "TBC",
    catalyst: "TBC",
    verdict: "PENDING",
    score: null,
    timingConfidence: "reported",
  },
];
