import type { Project } from "../types";

// Sample project so the verdict page can be reviewed before any real project file exists.
// Market and pricing data (from URA/developers) is genuinely unavailable in Phase 1, so
// those fields stay null and render as bracketed placeholders. Scoring criteria are the
// advisor's own judgement (not external market fact), so they carry sample ratings here
// to demonstrate the scorecards, weighting and profile switch working end to end.
export const demoProject: Project = {
  slug: "demo-project",
  name: "Demo Project — sample verdict walkthrough",
  district: "[District]",
  region: "OCR",
  tenure: "[Tenure]",
  totalUnits: null,
  developer: "[Developer]",
  previewDate: "[Preview date]",
  expectedTop: "[Expected TOP]",
  verdict: "CONDITIONAL",
  score: 61,
  thesis:
    "This is a sample verdict, built so the page layout can be reviewed before real pricing and supply data are loaded. Replace every bracketed field with the advisor's own research once a live project file is ready.",
  reviewedBy: "[Advisor name]",
  reviewedOn: "[Review date]",
  fundamentals: [
    {
      name: "Location and connectivity",
      measure: "Walk time to MRT, schools within 1km, daily amenities",
      rule: "Green if MRT is within a 10 minute walk",
      result: "Meets the MRT walk-time rule",
      score: 8,
    },
    {
      name: "Entry price versus land cost",
      measure: "Launch psf against developer breakeven psf",
      rule: "Green if the margin is 15% or less",
      result: "Meets the entry-price rule",
      score: 7,
    },
    {
      name: "Competing supply",
      measure: "Uncompleted private units within 2km, including upcoming GLS",
      rule: "Green if under 2,000 units",
      result: "Meets the competing-supply rule",
      score: 6,
    },
    {
      name: "Catalysts before exit",
      measure: "Master Plan items, new MRT lines, hubs landing before the exit year",
      rule: "Green if at least one lands by year 7",
      result: "At least one catalyst lands within 7 years",
      score: 7,
    },
    {
      name: "Exit buyer pool",
      measure: "Exit quantum against HDB upgrader budgets in nearby towns",
      rule: "Green if the exit price is within upgrader reach",
      result: "Exit quantum sits within upgrader reach",
      score: 6,
    },
    {
      name: "Rental demand",
      measure: "Estimated gross yield and tenant pool",
      rule: "Green if gross yield is 3.0% or more",
      result: "Falls just short of the yield rule",
      score: 5,
    },
  ],
  technicals: [
    {
      name: "New launch premium",
      measure: "Launch psf versus 5 to 10 year old condos within 1km",
      rule: "Green if 15% or less",
      result: "Falls short of the premium rule",
      score: 5,
    },
    {
      name: "District trend",
      measure: "4-quarter versus 8-quarter moving average of resale psf",
      rule: "Green if the 4Q average is above the 8Q",
      result: "4Q average sits below the 8Q average",
      score: 5,
    },
    {
      name: "Sales momentum",
      measure: "Launch weekend take-up, then units sold per month",
      rule: "Green if 30% or more sold at launch",
      result: "Meets the launch take-up rule",
      score: 6,
    },
    {
      name: "Phase pricing",
      measure: "Developer price increases since launch, by stack",
      rule: "Green if increases are under 5% so far",
      result: "Meets the phase-pricing rule",
      score: 5,
    },
    {
      name: "Nearby launch absorption",
      measure: "Sell-through of launches within 2km in the last 24 months",
      rule: "Green if 70% or more sold",
      result: "Falls just short of the absorption rule",
      score: 5,
    },
    {
      name: "Volume signal",
      measure: "District transactions versus the same period last year",
      rule: "Green if volume is flat or rising",
      result: "Volume is roughly flat year on year",
      score: 4,
    },
  ],
  pricing: {
    resale10yrPsf: null,
    resale5to10yrPsf: null,
    recentLaunchPsf: null,
    thisProjectPsfLow: null,
    thisProjectPsfHigh: null,
    breakevenPsf: null,
  },
  breakeven: {
    landPsfPpr: null,
    construction: null,
    financeAndFees: null,
    breakeven: null,
    avgLaunchPsf: null,
    absdDeadline: null,
  },
  versus: {
    budget: null,
    unitType: null,
    holdingYears: null,
    rows: [
      { label: "Unit and size", newLaunch: null, resale: null },
      { label: "Price and psf", newLaunch: null, resale: null },
      { label: "Building age at exit", newLaunch: null, resale: null },
      { label: "Cash and loan before keys", newLaunch: null, resale: null },
      { label: "Rent or stay before TOP", newLaunch: null, resale: null },
      { label: "Estimated instalment at TOP", newLaunch: null, resale: null },
      { label: "Where upside comes from", newLaunch: null, resale: null },
      { label: "Main risk", newLaunch: null, resale: null },
      { label: "Stamp duties", newLaunch: null, resale: null },
    ],
    betterForYou: { verdict: null, note: null },
  },
  exitTest: {
    exitPriceFlatCase: null,
    upgraderBudget: null,
    competingSupplyUnits: null,
    leaseLeftAtExit: null,
  },
  catalysts: ["[Catalyst 1]", "[Catalyst 2]", "[Catalyst 3]"],
  risks: ["[Risk 1]", "[Risk 2]", "[Risk 3]"],
  wouldChangeView: ["[Condition 1 that would change our view]", "[Condition 2]", "[Condition 3]"],
};
